services:
  console:
    image: ghcr.io/c-ciobanu/popcorn-time-console:${COMMIT_SHA}
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
