services:
  console:
    image: ghcr.io/c-ciobanu/popcorn-time-console:${COMMIT_SHA}
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
      - MINIO_API_URL=${MINIO_API_URL}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
