packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-core": 0.13.8
  "@tailwindcss/postcss": 4.1.16
  "@types/node": 22.18.12
  prettier: 3.6.2
  typescript: 5.9.3
  zod: 4.1.12

catalogs:
  eslint:
    "@eslint/js": 9.38.0
    eslint: 9.38.0
  better-auth:
    "@better-auth/cli": 1.3.32
    better-auth: 1.3.32
  orpc:
    "@orpc/client": 1.10.2
    "@orpc/server": 1.10.2
  # Update Dockerfile runner-server
  prisma:
    "prisma": 6.18.0
    "@prisma/client": 6.18.0
    "@prisma/adapter-pg": 6.18.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
