/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as ToDoListsRouteImport } from './routes/to-do-lists'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as ShoppingListsRouteImport } from './routes/shopping-lists'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MangasRouteImport } from './routes/mangas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsPomodoroRouteImport } from './routes/tools.pomodoro'
import { Route as ToDoListsIdRouteImport } from './routes/to-do-lists_.$id'
import { Route as ShowsTmdbIdRouteImport } from './routes/shows_.$tmdbId'
import { Route as ShoppingListsIdRouteImport } from './routes/shopping-lists_.$id'
import { Route as SearchShowsRouteImport } from './routes/search.shows'
import { Route as SearchMoviesRouteImport } from './routes/search.movies'
import { Route as SearchMangasRouteImport } from './routes/search.mangas'
import { Route as SearchBooksRouteImport } from './routes/search.books'
import { Route as MoviesTmdbIdRouteImport } from './routes/movies_.$tmdbId'
import { Route as MetricsIdRouteImport } from './routes/metrics_.$id'
import { Route as MangasMangaDexIdRouteImport } from './routes/mangas_.$mangaDexId'
import { Route as LoginDemoRouteImport } from './routes/login_.demo'
import { Route as InvoicesNewRouteImport } from './routes/invoices_.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices_.$id'
import { Route as DocumentsIdRouteImport } from './routes/documents_.$id'
import { Route as BooksGoogleIdRouteImport } from './routes/books_.$googleId'
import { Route as InvoicesIdPreviewRouteImport } from './routes/invoices_.$id_.preview'
import { Route as ShowsTmdbIdSeasonsNumberRouteImport } from './routes/shows_.$tmdbId_.seasons.$number'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ToDoListsRoute = ToDoListsRouteImport.update({
  id: '/to-do-lists',
  path: '/to-do-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsRoute = ShoppingListsRouteImport.update({
  id: '/shopping-lists',
  path: '/shopping-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MangasRoute = MangasRouteImport.update({
  id: '/mangas',
  path: '/mangas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPomodoroRoute = ToolsPomodoroRouteImport.update({
  id: '/tools/pomodoro',
  path: '/tools/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const ToDoListsIdRoute = ToDoListsIdRouteImport.update({
  id: '/to-do-lists_/$id',
  path: '/to-do-lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsTmdbIdRoute = ShowsTmdbIdRouteImport.update({
  id: '/shows_/$tmdbId',
  path: '/shows/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsIdRoute = ShoppingListsIdRouteImport.update({
  id: '/shopping-lists_/$id',
  path: '/shopping-lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchShowsRoute = SearchShowsRouteImport.update({
  id: '/search/shows',
  path: '/search/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMoviesRoute = SearchMoviesRouteImport.update({
  id: '/search/movies',
  path: '/search/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMangasRoute = SearchMangasRouteImport.update({
  id: '/search/mangas',
  path: '/search/mangas',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchBooksRoute = SearchBooksRouteImport.update({
  id: '/search/books',
  path: '/search/books',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesTmdbIdRoute = MoviesTmdbIdRouteImport.update({
  id: '/movies_/$tmdbId',
  path: '/movies/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIdRoute = MetricsIdRouteImport.update({
  id: '/metrics_/$id',
  path: '/metrics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangasMangaDexIdRoute = MangasMangaDexIdRouteImport.update({
  id: '/mangas_/$mangaDexId',
  path: '/mangas/$mangaDexId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDemoRoute = LoginDemoRouteImport.update({
  id: '/login_/demo',
  path: '/login/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices_/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices_/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents_/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksGoogleIdRoute = BooksGoogleIdRouteImport.update({
  id: '/books_/$googleId',
  path: '/books/$googleId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdPreviewRoute = InvoicesIdPreviewRouteImport.update({
  id: '/invoices_/$id_/preview',
  path: '/invoices/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsTmdbIdSeasonsNumberRoute =
  ShowsTmdbIdSeasonsNumberRouteImport.update({
    id: '/shows_/$tmdbId_/seasons/$number',
    path: '/shows/$tmdbId/seasons/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/mangas': typeof MangasRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/to-do-lists': typeof ToDoListsRoute
  '/workouts': typeof WorkoutsRoute
  '/books/$googleId': typeof BooksGoogleIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/login/demo': typeof LoginDemoRoute
  '/mangas/$mangaDexId': typeof MangasMangaDexIdRoute
  '/metrics/$id': typeof MetricsIdRoute
  '/movies/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/mangas': typeof SearchMangasRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRoute
  '/shows/$tmdbId': typeof ShowsTmdbIdRoute
  '/to-do-lists/$id': typeof ToDoListsIdRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/invoices/$id/preview': typeof InvoicesIdPreviewRoute
  '/shows/$tmdbId/seasons/$number': typeof ShowsTmdbIdSeasonsNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/mangas': typeof MangasRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/to-do-lists': typeof ToDoListsRoute
  '/workouts': typeof WorkoutsRoute
  '/books/$googleId': typeof BooksGoogleIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/login/demo': typeof LoginDemoRoute
  '/mangas/$mangaDexId': typeof MangasMangaDexIdRoute
  '/metrics/$id': typeof MetricsIdRoute
  '/movies/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/mangas': typeof SearchMangasRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRoute
  '/shows/$tmdbId': typeof ShowsTmdbIdRoute
  '/to-do-lists/$id': typeof ToDoListsIdRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/invoices/$id/preview': typeof InvoicesIdPreviewRoute
  '/shows/$tmdbId/seasons/$number': typeof ShowsTmdbIdSeasonsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/mangas': typeof MangasRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/shopping-lists': typeof ShoppingListsRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/to-do-lists': typeof ToDoListsRoute
  '/workouts': typeof WorkoutsRoute
  '/books_/$googleId': typeof BooksGoogleIdRoute
  '/documents_/$id': typeof DocumentsIdRoute
  '/invoices_/$id': typeof InvoicesIdRoute
  '/invoices_/new': typeof InvoicesNewRoute
  '/login_/demo': typeof LoginDemoRoute
  '/mangas_/$mangaDexId': typeof MangasMangaDexIdRoute
  '/metrics_/$id': typeof MetricsIdRoute
  '/movies_/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/mangas': typeof SearchMangasRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/shopping-lists_/$id': typeof ShoppingListsIdRoute
  '/shows_/$tmdbId': typeof ShowsTmdbIdRoute
  '/to-do-lists_/$id': typeof ToDoListsIdRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
  '/invoices_/$id_/preview': typeof InvoicesIdPreviewRoute
  '/shows_/$tmdbId_/seasons/$number': typeof ShowsTmdbIdSeasonsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/dashboard'
    | '/documents'
    | '/files'
    | '/invoices'
    | '/login'
    | '/mangas'
    | '/metrics'
    | '/movies'
    | '/settings'
    | '/shopping-lists'
    | '/shows'
    | '/signup'
    | '/to-do-lists'
    | '/workouts'
    | '/books/$googleId'
    | '/documents/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/login/demo'
    | '/mangas/$mangaDexId'
    | '/metrics/$id'
    | '/movies/$tmdbId'
    | '/search/books'
    | '/search/mangas'
    | '/search/movies'
    | '/search/shows'
    | '/shopping-lists/$id'
    | '/shows/$tmdbId'
    | '/to-do-lists/$id'
    | '/tools/pomodoro'
    | '/invoices/$id/preview'
    | '/shows/$tmdbId/seasons/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/dashboard'
    | '/documents'
    | '/files'
    | '/invoices'
    | '/login'
    | '/mangas'
    | '/metrics'
    | '/movies'
    | '/settings'
    | '/shopping-lists'
    | '/shows'
    | '/signup'
    | '/to-do-lists'
    | '/workouts'
    | '/books/$googleId'
    | '/documents/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/login/demo'
    | '/mangas/$mangaDexId'
    | '/metrics/$id'
    | '/movies/$tmdbId'
    | '/search/books'
    | '/search/mangas'
    | '/search/movies'
    | '/search/shows'
    | '/shopping-lists/$id'
    | '/shows/$tmdbId'
    | '/to-do-lists/$id'
    | '/tools/pomodoro'
    | '/invoices/$id/preview'
    | '/shows/$tmdbId/seasons/$number'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/dashboard'
    | '/documents'
    | '/files'
    | '/invoices'
    | '/login'
    | '/mangas'
    | '/metrics'
    | '/movies'
    | '/settings'
    | '/shopping-lists'
    | '/shows'
    | '/signup'
    | '/to-do-lists'
    | '/workouts'
    | '/books_/$googleId'
    | '/documents_/$id'
    | '/invoices_/$id'
    | '/invoices_/new'
    | '/login_/demo'
    | '/mangas_/$mangaDexId'
    | '/metrics_/$id'
    | '/movies_/$tmdbId'
    | '/search/books'
    | '/search/mangas'
    | '/search/movies'
    | '/search/shows'
    | '/shopping-lists_/$id'
    | '/shows_/$tmdbId'
    | '/to-do-lists_/$id'
    | '/tools/pomodoro'
    | '/invoices_/$id_/preview'
    | '/shows_/$tmdbId_/seasons/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FilesRoute: typeof FilesRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MangasRoute: typeof MangasRoute
  MetricsRoute: typeof MetricsRoute
  MoviesRoute: typeof MoviesRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingListsRoute: typeof ShoppingListsRoute
  ShowsRoute: typeof ShowsRoute
  SignupRoute: typeof SignupRoute
  ToDoListsRoute: typeof ToDoListsRoute
  WorkoutsRoute: typeof WorkoutsRoute
  BooksGoogleIdRoute: typeof BooksGoogleIdRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  LoginDemoRoute: typeof LoginDemoRoute
  MangasMangaDexIdRoute: typeof MangasMangaDexIdRoute
  MetricsIdRoute: typeof MetricsIdRoute
  MoviesTmdbIdRoute: typeof MoviesTmdbIdRoute
  SearchBooksRoute: typeof SearchBooksRoute
  SearchMangasRoute: typeof SearchMangasRoute
  SearchMoviesRoute: typeof SearchMoviesRoute
  SearchShowsRoute: typeof SearchShowsRoute
  ShoppingListsIdRoute: typeof ShoppingListsIdRoute
  ShowsTmdbIdRoute: typeof ShowsTmdbIdRoute
  ToDoListsIdRoute: typeof ToDoListsIdRoute
  ToolsPomodoroRoute: typeof ToolsPomodoroRoute
  InvoicesIdPreviewRoute: typeof InvoicesIdPreviewRoute
  ShowsTmdbIdSeasonsNumberRoute: typeof ShowsTmdbIdSeasonsNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-do-lists': {
      id: '/to-do-lists'
      path: '/to-do-lists'
      fullPath: '/to-do-lists'
      preLoaderRoute: typeof ToDoListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists': {
      id: '/shopping-lists'
      path: '/shopping-lists'
      fullPath: '/shopping-lists'
      preLoaderRoute: typeof ShoppingListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangas': {
      id: '/mangas'
      path: '/mangas'
      fullPath: '/mangas'
      preLoaderRoute: typeof MangasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pomodoro': {
      id: '/tools/pomodoro'
      path: '/tools/pomodoro'
      fullPath: '/tools/pomodoro'
      preLoaderRoute: typeof ToolsPomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-do-lists_/$id': {
      id: '/to-do-lists_/$id'
      path: '/to-do-lists/$id'
      fullPath: '/to-do-lists/$id'
      preLoaderRoute: typeof ToDoListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows_/$tmdbId': {
      id: '/shows_/$tmdbId'
      path: '/shows/$tmdbId'
      fullPath: '/shows/$tmdbId'
      preLoaderRoute: typeof ShowsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists_/$id': {
      id: '/shopping-lists_/$id'
      path: '/shopping-lists/$id'
      fullPath: '/shopping-lists/$id'
      preLoaderRoute: typeof ShoppingListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/shows': {
      id: '/search/shows'
      path: '/search/shows'
      fullPath: '/search/shows'
      preLoaderRoute: typeof SearchShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/movies': {
      id: '/search/movies'
      path: '/search/movies'
      fullPath: '/search/movies'
      preLoaderRoute: typeof SearchMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/mangas': {
      id: '/search/mangas'
      path: '/search/mangas'
      fullPath: '/search/mangas'
      preLoaderRoute: typeof SearchMangasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/books': {
      id: '/search/books'
      path: '/search/books'
      fullPath: '/search/books'
      preLoaderRoute: typeof SearchBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies_/$tmdbId': {
      id: '/movies_/$tmdbId'
      path: '/movies/$tmdbId'
      fullPath: '/movies/$tmdbId'
      preLoaderRoute: typeof MoviesTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics_/$id': {
      id: '/metrics_/$id'
      path: '/metrics/$id'
      fullPath: '/metrics/$id'
      preLoaderRoute: typeof MetricsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangas_/$mangaDexId': {
      id: '/mangas_/$mangaDexId'
      path: '/mangas/$mangaDexId'
      fullPath: '/mangas/$mangaDexId'
      preLoaderRoute: typeof MangasMangaDexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/demo': {
      id: '/login_/demo'
      path: '/login/demo'
      fullPath: '/login/demo'
      preLoaderRoute: typeof LoginDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/new': {
      id: '/invoices_/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$id': {
      id: '/invoices_/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$id': {
      id: '/documents_/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books_/$googleId': {
      id: '/books_/$googleId'
      path: '/books/$googleId'
      fullPath: '/books/$googleId'
      preLoaderRoute: typeof BooksGoogleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$id_/preview': {
      id: '/invoices_/$id_/preview'
      path: '/invoices/$id/preview'
      fullPath: '/invoices/$id/preview'
      preLoaderRoute: typeof InvoicesIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows_/$tmdbId_/seasons/$number': {
      id: '/shows_/$tmdbId_/seasons/$number'
      path: '/shows/$tmdbId/seasons/$number'
      fullPath: '/shows/$tmdbId/seasons/$number'
      preLoaderRoute: typeof ShowsTmdbIdSeasonsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FilesRoute: FilesRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MangasRoute: MangasRoute,
  MetricsRoute: MetricsRoute,
  MoviesRoute: MoviesRoute,
  SettingsRoute: SettingsRoute,
  ShoppingListsRoute: ShoppingListsRoute,
  ShowsRoute: ShowsRoute,
  SignupRoute: SignupRoute,
  ToDoListsRoute: ToDoListsRoute,
  WorkoutsRoute: WorkoutsRoute,
  BooksGoogleIdRoute: BooksGoogleIdRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  LoginDemoRoute: LoginDemoRoute,
  MangasMangaDexIdRoute: MangasMangaDexIdRoute,
  MetricsIdRoute: MetricsIdRoute,
  MoviesTmdbIdRoute: MoviesTmdbIdRoute,
  SearchBooksRoute: SearchBooksRoute,
  SearchMangasRoute: SearchMangasRoute,
  SearchMoviesRoute: SearchMoviesRoute,
  SearchShowsRoute: SearchShowsRoute,
  ShoppingListsIdRoute: ShoppingListsIdRoute,
  ShowsTmdbIdRoute: ShowsTmdbIdRoute,
  ToDoListsIdRoute: ToDoListsIdRoute,
  ToolsPomodoroRoute: ToolsPomodoroRoute,
  InvoicesIdPreviewRoute: InvoicesIdPreviewRoute,
  ShowsTmdbIdSeasonsNumberRoute: ShowsTmdbIdSeasonsNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
