/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsPomodoroRouteImport } from './routes/tools.pomodoro'
import { Route as SearchShowsRouteImport } from './routes/search.shows'
import { Route as SearchMoviesRouteImport } from './routes/search.movies'
import { Route as SearchBooksRouteImport } from './routes/search.books'
import { Route as MoviesTmdbIdRouteImport } from './routes/movies_.$tmdbId'
import { Route as MetricsIdRouteImport } from './routes/metrics_.$id'
import { Route as LoginDemoRouteImport } from './routes/login_.demo'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPomodoroRoute = ToolsPomodoroRouteImport.update({
  id: '/tools/pomodoro',
  path: '/tools/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchShowsRoute = SearchShowsRouteImport.update({
  id: '/search/shows',
  path: '/search/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMoviesRoute = SearchMoviesRouteImport.update({
  id: '/search/movies',
  path: '/search/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchBooksRoute = SearchBooksRouteImport.update({
  id: '/search/books',
  path: '/search/books',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesTmdbIdRoute = MoviesTmdbIdRouteImport.update({
  id: '/movies_/$tmdbId',
  path: '/movies/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIdRoute = MetricsIdRouteImport.update({
  id: '/metrics_/$id',
  path: '/metrics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDemoRoute = LoginDemoRouteImport.update({
  id: '/login_/demo',
  path: '/login/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/login/demo': typeof LoginDemoRoute
  '/metrics/$id': typeof MetricsIdRoute
  '/movies/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/login/demo': typeof LoginDemoRoute
  '/metrics/$id': typeof MetricsIdRoute
  '/movies/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRoute
  '/signup': typeof SignupRoute
  '/workouts': typeof WorkoutsRoute
  '/login_/demo': typeof LoginDemoRoute
  '/metrics_/$id': typeof MetricsIdRoute
  '/movies_/$tmdbId': typeof MoviesTmdbIdRoute
  '/search/books': typeof SearchBooksRoute
  '/search/movies': typeof SearchMoviesRoute
  '/search/shows': typeof SearchShowsRoute
  '/tools/pomodoro': typeof ToolsPomodoroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/documents'
    | '/invoices'
    | '/login'
    | '/metrics'
    | '/movies'
    | '/shows'
    | '/signup'
    | '/workouts'
    | '/login/demo'
    | '/metrics/$id'
    | '/movies/$tmdbId'
    | '/search/books'
    | '/search/movies'
    | '/search/shows'
    | '/tools/pomodoro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/documents'
    | '/invoices'
    | '/login'
    | '/metrics'
    | '/movies'
    | '/shows'
    | '/signup'
    | '/workouts'
    | '/login/demo'
    | '/metrics/$id'
    | '/movies/$tmdbId'
    | '/search/books'
    | '/search/movies'
    | '/search/shows'
    | '/tools/pomodoro'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/documents'
    | '/invoices'
    | '/login'
    | '/metrics'
    | '/movies'
    | '/shows'
    | '/signup'
    | '/workouts'
    | '/login_/demo'
    | '/metrics_/$id'
    | '/movies_/$tmdbId'
    | '/search/books'
    | '/search/movies'
    | '/search/shows'
    | '/tools/pomodoro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  DocumentsRoute: typeof DocumentsRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  MoviesRoute: typeof MoviesRoute
  ShowsRoute: typeof ShowsRoute
  SignupRoute: typeof SignupRoute
  WorkoutsRoute: typeof WorkoutsRoute
  LoginDemoRoute: typeof LoginDemoRoute
  MetricsIdRoute: typeof MetricsIdRoute
  MoviesTmdbIdRoute: typeof MoviesTmdbIdRoute
  SearchBooksRoute: typeof SearchBooksRoute
  SearchMoviesRoute: typeof SearchMoviesRoute
  SearchShowsRoute: typeof SearchShowsRoute
  ToolsPomodoroRoute: typeof ToolsPomodoroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pomodoro': {
      id: '/tools/pomodoro'
      path: '/tools/pomodoro'
      fullPath: '/tools/pomodoro'
      preLoaderRoute: typeof ToolsPomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/shows': {
      id: '/search/shows'
      path: '/search/shows'
      fullPath: '/search/shows'
      preLoaderRoute: typeof SearchShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/movies': {
      id: '/search/movies'
      path: '/search/movies'
      fullPath: '/search/movies'
      preLoaderRoute: typeof SearchMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/books': {
      id: '/search/books'
      path: '/search/books'
      fullPath: '/search/books'
      preLoaderRoute: typeof SearchBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies_/$tmdbId': {
      id: '/movies_/$tmdbId'
      path: '/movies/$tmdbId'
      fullPath: '/movies/$tmdbId'
      preLoaderRoute: typeof MoviesTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics_/$id': {
      id: '/metrics_/$id'
      path: '/metrics/$id'
      fullPath: '/metrics/$id'
      preLoaderRoute: typeof MetricsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/demo': {
      id: '/login_/demo'
      path: '/login/demo'
      fullPath: '/login/demo'
      preLoaderRoute: typeof LoginDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  DocumentsRoute: DocumentsRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  MoviesRoute: MoviesRoute,
  ShowsRoute: ShowsRoute,
  SignupRoute: SignupRoute,
  WorkoutsRoute: WorkoutsRoute,
  LoginDemoRoute: LoginDemoRoute,
  MetricsIdRoute: MetricsIdRoute,
  MoviesTmdbIdRoute: MoviesTmdbIdRoute,
  SearchBooksRoute: SearchBooksRoute,
  SearchMoviesRoute: SearchMoviesRoute,
  SearchShowsRoute: SearchShowsRoute,
  ToolsPomodoroRoute: ToolsPomodoroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
